export const memesList = [
  {
    id: 1,
    title: "Doge",
    image: "https://i.imgur.com/9nC5V.jpg",
    likes: Math.floor(Math.random() * 100),
    link: "https://knowyourmeme.com/memes/doge",
  },
  {
    id: 2,
    title: "Distracted Boyfriend",
    image: "https://i.imgur.com/Jv4LxPI.jpg",
    likes: Math.floor(Math.random() * 100),
    link: "https://knowyourmeme.com/memes/distracted-boyfriend",
  },
  {
    id: 3,
    title: "Woman Yelling at a Cat",
    image: "https://i.imgur.com/Xq3F4lY.jpg",
    likes: Math.floor(Math.random() * 100),
    link: "https://knowyourmeme.com/memes/woman-yelling-at-a-cat",
  },
  {
    id: 4,
    title: "Success Kid",
    image: "https://i.imgur.com/QUzLdfc.jpg",
    likes: Math.floor(Math.random() * 100),
    link: "https://knowyourmeme.com/memes/success-kid",
  },
  {
    id: 5,
    title: "Hide the Pain Harold",
    image: "https://i.imgur.com/2P2qYl1.jpg",
    likes: Math.floor(Math.random() * 100),
    link: "https://knowyourmeme.com/memes/hide-the-pain-harold",
  },
  {
    id: 6,
    title: "Drakeposting",
    image: "https://i.imgur.com/DckVpEY.jpg",
    likes: Math.floor(Math.random() * 100),
    link: "https://knowyourmeme.com/memes/drakeposting",
  },
  {
    id: 7,
    title: "Is This a Pigeon?",
    image: "https://i.imgur.com/Zv2ZxRt.jpg",
    likes: Math.floor(Math.random() * 100),
    link: "https://knowyourmeme.com/memes/is-this-a-pigeon",
  },
  {
    id: 8,
    title: "Change My Mind",
    image: "https://i.imgur.com/T8jQdGA.jpg",
    likes: Math.floor(Math.random() * 100),
    link: "https://knowyourmeme.com/memes/change-my-mind",
  },
  {
    id: 9,
    title: "This Is Fine",
    image: "https://i.imgur.com/SJH6N0h.jpg",
    likes: Math.floor(Math.random() * 100),
    link: "https://knowyourmeme.com/memes/this-is-fine",
  },
  {
    id: 10,
    title: "One Does Not Simply",
    image: "https://i.imgur.com/TxjBqcf.jpg",
    likes: Math.floor(Math.random() * 100),
    link: "https://knowyourmeme.com/memes/one-does-not-simply-walk-into-mordor",
  },
];
